html_tag:
  small_section: "sx2jih0 zcydq86a"
  company_name: "sx2jih0 zcydq84u es8sxo0 es8sxo2 es8sxo21 _1d0g9qk4 es8sxoa"
  add_info: "sx2jih0 zcydq8n zcydq86q zcydq89q"
  company_overview : "sx2jih0 zcydq86q zcydq86v zcydq86w"

settings:
  pages: 2
  search_term: "Data-scientist"
  jobstreet_main_link : 'http://www.jobstreet.com.sg'
  jobstreet_search_link : 'http://www.jobstreet.com.sg/en/job-search/'